version: '2'
services:
  db:
    build: .
    volumes:
      - ./docs:/src/docs:z
      - ./cnxdb:/src/cnxdb:z
      - ./htmlcov:/src/htmlcov:z
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg-data: